CC = gcc
CFLAGS = -std=gnu99 -Wall -Wextra

SRC = crudPRODUCTOS.c
# I often specify the targetted output as the name of the project.
TARGET = crudPRODUCTOS

all:
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET) && .\$(TARGET)
