CC = gcc
CFLAGS = -std=gnu99 -Wall -Wextra

SRC = crudMOVC.c
# I often specify the targetted output as the name of the project.
TARGET = crudMOVC

all:
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET) && .\$(TARGET)
