CC = gcc
CFLAGS = -std=gnu99 -Wall -Wextra

SRC = LinkedList_CRUD.c
# I often specify the targetted output as the name of the project.
TARGET = LinkedList_CRUD

all:
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET) && .\$(TARGET)
